# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.15.9

# This file contains the python codes of the application prepared by 
# the void team for the teknofest "model satellite" competition.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_theVoid(object):
    def setupUi(self, theVoid):
        theVoid.setObjectName("theVoid")
        theVoid.resize(1319, 871)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(theVoid.sizePolicy().hasHeightForWidth())
        theVoid.setSizePolicy(sizePolicy)
        theVoid.setMinimumSize(QtCore.QSize(800, 600))
        theVoid.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(theVoid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.section1 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section1.sizePolicy().hasHeightForWidth())
        self.section1.setSizePolicy(sizePolicy)
        self.section1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.section1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.section1.setObjectName("section1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.section1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlAndInfo = QtWidgets.QFrame(self.section1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlAndInfo.sizePolicy().hasHeightForWidth())
        self.controlAndInfo.setSizePolicy(sizePolicy)
        self.controlAndInfo.setStyleSheet("")
        self.controlAndInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlAndInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlAndInfo.setObjectName("controlAndInfo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.controlAndInfo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aboutAndConnection = QtWidgets.QFrame(self.controlAndInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutAndConnection.sizePolicy().hasHeightForWidth())
        self.aboutAndConnection.setSizePolicy(sizePolicy)
        self.aboutAndConnection.setStyleSheet("")
        self.aboutAndConnection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aboutAndConnection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aboutAndConnection.setObjectName("aboutAndConnection")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.aboutAndConnection)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoAndId = QtWidgets.QFrame(self.aboutAndConnection)
        self.logoAndId.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoAndId.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoAndId.setObjectName("logoAndId")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.logoAndId)
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo = QtWidgets.QLabel(self.logoAndId)
        self.logo.setStyleSheet("image: url(:/logo/logo.svg);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        self.teamNo = QtWidgets.QLabel(self.logoAndId)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.teamNo.setFont(font)
        self.teamNo.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.teamNo.setAlignment(QtCore.Qt.AlignCenter)
        self.teamNo.setObjectName("teamNo")
        self.verticalLayout_3.addWidget(self.teamNo)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.logoAndId)
        self.connectMenu = QtWidgets.QFrame(self.aboutAndConnection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectMenu.sizePolicy().hasHeightForWidth())
        self.connectMenu.setSizePolicy(sizePolicy)
        self.connectMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectMenu.setObjectName("connectMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.connectMenu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.infoConnect = QtWidgets.QFrame(self.connectMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoConnect.sizePolicy().hasHeightForWidth())
        self.infoConnect.setSizePolicy(sizePolicy)
        self.infoConnect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoConnect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoConnect.setObjectName("infoConnect")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.infoConnect)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.infoTitle = QtWidgets.QLabel(self.infoConnect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoTitle.sizePolicy().hasHeightForWidth())
        self.infoTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.infoTitle.setFont(font)
        self.infoTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.infoTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.infoTitle.setObjectName("infoTitle")
        self.horizontalLayout_3.addWidget(self.infoTitle)
        self.connectButton = QtWidgets.QPushButton(self.infoConnect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.connectButton.setFont(font)
        self.connectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_3.addWidget(self.connectButton)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_5.addWidget(self.infoConnect)
        self.ipPortBaudRate = QtWidgets.QFrame(self.connectMenu)
        self.ipPortBaudRate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ipPortBaudRate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ipPortBaudRate.setObjectName("ipPortBaudRate")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ipPortBaudRate)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ipArea = QtWidgets.QFrame(self.ipPortBaudRate)
        self.ipArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ipArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ipArea.setObjectName("ipArea")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ipArea)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ipTitle = QtWidgets.QLabel(self.ipArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.ipTitle.setFont(font)
        self.ipTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipTitle.setObjectName("ipTitle")
        self.horizontalLayout_4.addWidget(self.ipTitle)
        self.ipInput = QtWidgets.QLineEdit(self.ipArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.ipInput.setFont(font)
        self.ipInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 37, 37);\n"
"border: 0;")
        self.ipInput.setObjectName("ipInput")
        self.horizontalLayout_4.addWidget(self.ipInput)
        self.verticalLayout_6.addWidget(self.ipArea)
        self.portArea = QtWidgets.QFrame(self.ipPortBaudRate)
        self.portArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.portArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.portArea.setObjectName("portArea")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.portArea)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.portTitle = QtWidgets.QLabel(self.portArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portTitle.sizePolicy().hasHeightForWidth())
        self.portTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.portTitle.setFont(font)
        self.portTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.portTitle.setObjectName("portTitle")
        self.horizontalLayout_5.addWidget(self.portTitle)
        self.portDataList = QtWidgets.QComboBox(self.portArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.portDataList.setFont(font)
        self.portDataList.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 37, 37);\n"
"border: 0;")
        self.portDataList.setObjectName("portDataList")
        self.portDataList.addItem("")
        self.portDataList.addItem("")
        self.portDataList.addItem("")
        self.horizontalLayout_5.addWidget(self.portDataList)
        self.verticalLayout_6.addWidget(self.portArea)
        self.baudrateArea = QtWidgets.QFrame(self.ipPortBaudRate)
        self.baudrateArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baudrateArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baudrateArea.setObjectName("baudrateArea")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.baudrateArea)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.baudrateTitle = QtWidgets.QLabel(self.baudrateArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudrateTitle.sizePolicy().hasHeightForWidth())
        self.baudrateTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.baudrateTitle.setFont(font)
        self.baudrateTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.baudrateTitle.setObjectName("baudrateTitle")
        self.horizontalLayout_6.addWidget(self.baudrateTitle)
        self.baudrateDataList = QtWidgets.QComboBox(self.baudrateArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.baudrateDataList.setFont(font)
        self.baudrateDataList.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 37, 37);\n"
"border: 0;")
        self.baudrateDataList.setObjectName("baudrateDataList")
        self.horizontalLayout_6.addWidget(self.baudrateDataList)
        self.verticalLayout_6.addWidget(self.baudrateArea)
        self.verticalLayout_5.addWidget(self.ipPortBaudRate)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 3)
        self.horizontalLayout_2.addWidget(self.connectMenu)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.aboutAndConnection)
        self.timeAndFile = QtWidgets.QFrame(self.controlAndInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeAndFile.sizePolicy().hasHeightForWidth())
        self.timeAndFile.setSizePolicy(sizePolicy)
        self.timeAndFile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeAndFile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeAndFile.setObjectName("timeAndFile")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.timeAndFile)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.timeFrame = QtWidgets.QFrame(self.timeAndFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeFrame.sizePolicy().hasHeightForWidth())
        self.timeFrame.setSizePolicy(sizePolicy)
        self.timeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeFrame.setObjectName("timeFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.timeFrame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.liveTimeFrame = QtWidgets.QFrame(self.timeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liveTimeFrame.sizePolicy().hasHeightForWidth())
        self.liveTimeFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        self.liveTimeFrame.setFont(font)
        self.liveTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liveTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.liveTimeFrame.setObjectName("liveTimeFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.liveTimeFrame)
        self.horizontalLayout_8.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.liveTimeName = QtWidgets.QLabel(self.liveTimeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liveTimeName.sizePolicy().hasHeightForWidth())
        self.liveTimeName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.liveTimeName.setFont(font)
        self.liveTimeName.setStyleSheet("color: rgb(255, 255, 255);")
        self.liveTimeName.setObjectName("liveTimeName")
        self.horizontalLayout_8.addWidget(self.liveTimeName)
        self.liveTimeValue = QtWidgets.QLabel(self.liveTimeFrame)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.liveTimeValue.setFont(font)
        self.liveTimeValue.setStyleSheet("color: rgb(255, 255, 255);")
        self.liveTimeValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.liveTimeValue.setObjectName("liveTimeValue")
        self.horizontalLayout_8.addWidget(self.liveTimeValue)
        self.verticalLayout_7.addWidget(self.liveTimeFrame)
        self.startTimeFrame = QtWidgets.QFrame(self.timeFrame)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        self.startTimeFrame.setFont(font)
        self.startTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.startTimeFrame.setObjectName("startTimeFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.startTimeFrame)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startTimeName = QtWidgets.QLabel(self.startTimeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimeName.sizePolicy().hasHeightForWidth())
        self.startTimeName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.startTimeName.setFont(font)
        self.startTimeName.setStyleSheet("color: rgb(255, 255, 255);")
        self.startTimeName.setObjectName("startTimeName")
        self.horizontalLayout_9.addWidget(self.startTimeName)
        self.startTimeValue = QtWidgets.QLabel(self.startTimeFrame)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.startTimeValue.setFont(font)
        self.startTimeValue.setStyleSheet("color: rgb(255, 255, 255);")
        self.startTimeValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startTimeValue.setObjectName("startTimeValue")
        self.horizontalLayout_9.addWidget(self.startTimeValue)
        self.verticalLayout_7.addWidget(self.startTimeFrame)
        self.disconnectTimeFrame = QtWidgets.QFrame(self.timeFrame)
        self.disconnectTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.disconnectTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disconnectTimeFrame.setObjectName("disconnectTimeFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.disconnectTimeFrame)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.disconnectTime = QtWidgets.QLabel(self.disconnectTimeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectTime.sizePolicy().hasHeightForWidth())
        self.disconnectTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.disconnectTime.setFont(font)
        self.disconnectTime.setStyleSheet("color: rgb(255, 255, 255);")
        self.disconnectTime.setObjectName("disconnectTime")
        self.horizontalLayout_10.addWidget(self.disconnectTime)
        self.disconnectTimeValue = QtWidgets.QLabel(self.disconnectTimeFrame)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.disconnectTimeValue.setFont(font)
        self.disconnectTimeValue.setStyleSheet("color: rgb(255, 255, 255);")
        self.disconnectTimeValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disconnectTimeValue.setObjectName("disconnectTimeValue")
        self.horizontalLayout_10.addWidget(self.disconnectTimeValue)
        self.verticalLayout_7.addWidget(self.disconnectTimeFrame)
        self.downTimeFrame = QtWidgets.QFrame(self.timeFrame)
        self.downTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downTimeFrame.setObjectName("downTimeFrame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.downTimeFrame)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.downTimeName = QtWidgets.QLabel(self.downTimeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downTimeName.sizePolicy().hasHeightForWidth())
        self.downTimeName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.downTimeName.setFont(font)
        self.downTimeName.setStyleSheet("color: rgb(255, 255, 255);")
        self.downTimeName.setObjectName("downTimeName")
        self.horizontalLayout_17.addWidget(self.downTimeName)
        self.downTimeValue = QtWidgets.QLabel(self.downTimeFrame)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.downTimeValue.setFont(font)
        self.downTimeValue.setStyleSheet("color: rgb(255, 255, 255);")
        self.downTimeValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.downTimeValue.setObjectName("downTimeValue")
        self.horizontalLayout_17.addWidget(self.downTimeValue)
        self.verticalLayout_7.addWidget(self.downTimeFrame)
        self.totalTimeFrame = QtWidgets.QFrame(self.timeFrame)
        self.totalTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalTimeFrame.setObjectName("totalTimeFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.totalTimeFrame)
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.totalTimeName = QtWidgets.QLabel(self.totalTimeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTimeName.sizePolicy().hasHeightForWidth())
        self.totalTimeName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.totalTimeName.setFont(font)
        self.totalTimeName.setStyleSheet("color: rgb(255, 255, 255);")
        self.totalTimeName.setObjectName("totalTimeName")
        self.horizontalLayout_12.addWidget(self.totalTimeName)
        self.totalTimeValue = QtWidgets.QLabel(self.totalTimeFrame)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.totalTimeValue.setFont(font)
        self.totalTimeValue.setStyleSheet("color: rgb(255, 255, 255);")
        self.totalTimeValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalTimeValue.setObjectName("totalTimeValue")
        self.horizontalLayout_12.addWidget(self.totalTimeValue)
        self.verticalLayout_7.addWidget(self.totalTimeFrame)
        self.horizontalLayout_7.addWidget(self.timeFrame)
        self.fileSendFrame = QtWidgets.QFrame(self.timeAndFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSendFrame.sizePolicy().hasHeightForWidth())
        self.fileSendFrame.setSizePolicy(sizePolicy)
        self.fileSendFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileSendFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileSendFrame.setObjectName("fileSendFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fileSendFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fileFrame = QtWidgets.QFrame(self.fileSendFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileFrame.sizePolicy().hasHeightForWidth())
        self.fileFrame.setSizePolicy(sizePolicy)
        self.fileFrame.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 37, 37);")
        self.fileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileFrame.setObjectName("fileFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.fileFrame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.fileInput = QtWidgets.QLabel(self.fileFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileInput.sizePolicy().hasHeightForWidth())
        self.fileInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.fileInput.setFont(font)
        self.fileInput.setStyleSheet("color: rgb(255, 255, 255);")
        self.fileInput.setObjectName("fileInput")
        self.horizontalLayout_11.addWidget(self.fileInput)
        self.verticalLayout_8.addWidget(self.fileFrame)
        self.chooseButton = QtWidgets.QPushButton(self.fileSendFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseButton.sizePolicy().hasHeightForWidth())
        self.chooseButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.chooseButton.setFont(font)
        self.chooseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chooseButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.chooseButton.setObjectName("chooseButton")
        self.verticalLayout_8.addWidget(self.chooseButton)
        self.sendButton = QtWidgets.QPushButton(self.fileSendFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.sendButton.setFont(font)
        self.sendButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout_8.addWidget(self.sendButton)
        self.horizontalLayout_7.addWidget(self.fileSendFrame)
        self.verticalLayout_2.addWidget(self.timeAndFile)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout.addWidget(self.controlAndInfo)
        self.buttons = QtWidgets.QFrame(self.section1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons.sizePolicy().hasHeightForWidth())
        self.buttons.setSizePolicy(sizePolicy)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.buttons)
        self.verticalLayout_9.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.startButton = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout_9.addWidget(self.startButton)
        self.otherButtonSet = QtWidgets.QFrame(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherButtonSet.sizePolicy().hasHeightForWidth())
        self.otherButtonSet.setSizePolicy(sizePolicy)
        self.otherButtonSet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.otherButtonSet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.otherButtonSet.setObjectName("otherButtonSet")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.otherButtonSet)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buzzerButton = QtWidgets.QPushButton(self.otherButtonSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buzzerButton.sizePolicy().hasHeightForWidth())
        self.buzzerButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.buzzerButton.setFont(font)
        self.buzzerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buzzerButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.buzzerButton.setObjectName("buzzerButton")
        self.gridLayout_2.addWidget(self.buzzerButton, 0, 0, 1, 1)
        self.gpsButton = QtWidgets.QPushButton(self.otherButtonSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpsButton.sizePolicy().hasHeightForWidth())
        self.gpsButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.gpsButton.setFont(font)
        self.gpsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gpsButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.gpsButton.setObjectName("gpsButton")
        self.gridLayout_2.addWidget(self.gpsButton, 0, 1, 1, 1)
        self.cameraButton = QtWidgets.QPushButton(self.otherButtonSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraButton.sizePolicy().hasHeightForWidth())
        self.cameraButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.cameraButton.setFont(font)
        self.cameraButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cameraButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.cameraButton.setObjectName("cameraButton")
        self.gridLayout_2.addWidget(self.cameraButton, 0, 2, 1, 1)
        self.gyroButton = QtWidgets.QPushButton(self.otherButtonSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gyroButton.sizePolicy().hasHeightForWidth())
        self.gyroButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.gyroButton.setFont(font)
        self.gyroButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gyroButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.gyroButton.setObjectName("gyroButton")
        self.gridLayout_2.addWidget(self.gyroButton, 1, 0, 1, 1)
        self.disconnectButton = QtWidgets.QPushButton(self.otherButtonSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.disconnectButton.setFont(font)
        self.disconnectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.disconnectButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.disconnectButton.setObjectName("disconnectButton")
        self.gridLayout_2.addWidget(self.disconnectButton, 1, 1, 1, 1)
        self.preasureButton = QtWidgets.QPushButton(self.otherButtonSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preasureButton.sizePolicy().hasHeightForWidth())
        self.preasureButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.preasureButton.setFont(font)
        self.preasureButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.preasureButton.setStyleSheet("QPushButton {\n"
"\n"
"color: #ffffff;\n"
"background-color:#252525;\n"
"border-radius: 5px;\n"
"border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid #ffffff;\n"
"color: #000000;\n"
"background-color: #ffffff;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}")
        self.preasureButton.setObjectName("preasureButton")
        self.gridLayout_2.addWidget(self.preasureButton, 1, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.otherButtonSet)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout.addWidget(self.buttons)
        self.terminalArea = QtWidgets.QFrame(self.section1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalArea.sizePolicy().hasHeightForWidth())
        self.terminalArea.setSizePolicy(sizePolicy)
        self.terminalArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.terminalArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terminalArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terminalArea.setObjectName("terminalArea")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.terminalArea)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.terminalTitle = QtWidgets.QLabel(self.terminalArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(11)
        self.terminalTitle.setFont(font)
        self.terminalTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.terminalTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.terminalTitle.setObjectName("terminalTitle")
        self.verticalLayout_10.addWidget(self.terminalTitle)
        self.terminalScreen = QtWidgets.QTextBrowser(self.terminalArea)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(15)
        self.terminalScreen.setFont(font)
        self.terminalScreen.setStyleSheet("background-color:#000;\n"
"\n"
"border: 1px solid #454545;\n"
"border-radius: 7px;")
        self.terminalScreen.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminalScreen.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.terminalScreen.setSearchPaths([])
        self.terminalScreen.setObjectName("terminalScreen")
        self.verticalLayout_10.addWidget(self.terminalScreen)
        self.terminalCommandArea = QtWidgets.QFrame(self.terminalArea)
        self.terminalCommandArea.setStyleSheet("background-color: #000;\n"
"padding: 3px;\n"
"padding-left: 7px;\n"
"color: rgb(255, 255, 255);\n"
"margin-bottom: 3px;\n"
"\n"
"border: 1px solid #454545;\n"
"border-radius: 7px;")
        self.terminalCommandArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terminalCommandArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terminalCommandArea.setObjectName("terminalCommandArea")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.terminalCommandArea)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.terminalCommandInput = QtWidgets.QLineEdit(self.terminalCommandArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        self.terminalCommandInput.setFont(font)
        self.terminalCommandInput.setStyleSheet("\n"
"padding: 3px;\n"
"padding-left: 7px;\n"
"color: rgb(255, 255, 255);\n"
"margin-bottom: 3px;\n"
"\n"
"border: 0px solid #454545;\n"
"border-radius: 7px;")
        self.terminalCommandInput.setText("")
        self.terminalCommandInput.setPlaceholderText("command")
        self.terminalCommandInput.setObjectName("terminalCommandInput")
        self.horizontalLayout_13.addWidget(self.terminalCommandInput)
        self.sendButtonCommand = QtWidgets.QPushButton(self.terminalCommandArea)
        self.sendButtonCommand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendButtonCommand.setStyleSheet("image: url(:/icon/sendIcon.svg);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgba(255, 255, 255, 0);")
        self.sendButtonCommand.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sendIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.sendButtonCommand.setIcon(icon)
        self.sendButtonCommand.setIconSize(QtCore.QSize(20, 20))
        self.sendButtonCommand.setObjectName("sendButtonCommand")
        self.horizontalLayout_13.addWidget(self.sendButtonCommand)
        self.verticalLayout_10.addWidget(self.terminalCommandArea)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 10)
        self.verticalLayout.addWidget(self.terminalArea)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 4)
        self.horizontalLayout.addWidget(self.section1)
        self.section2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section2.sizePolicy().hasHeightForWidth())
        self.section2.setSizePolicy(sizePolicy)
        self.section2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.section2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.section2.setObjectName("section2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.section2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cameraArea = QtWidgets.QFrame(self.section2)
        self.cameraArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.cameraArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraArea.setObjectName("cameraArea")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.cameraArea)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cameraTitle = QtWidgets.QLabel(self.cameraArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraTitle.sizePolicy().hasHeightForWidth())
        self.cameraTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.cameraTitle.setFont(font)
        self.cameraTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.cameraTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraTitle.setObjectName("cameraTitle")
        self.verticalLayout_12.addWidget(self.cameraTitle)
        self.camera = QtWidgets.QWidget(self.cameraArea)
        self.camera.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.camera.setObjectName("camera")
        self.verticalLayout_12.addWidget(self.camera)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 5)
        self.verticalLayout_4.addWidget(self.cameraArea)
        self.humidityArea = QtWidgets.QFrame(self.section2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityArea.sizePolicy().hasHeightForWidth())
        self.humidityArea.setSizePolicy(sizePolicy)
        self.humidityArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.humidityArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.humidityArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.humidityArea.setObjectName("humidityArea")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.humidityArea)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.humidityTitle = QtWidgets.QLabel(self.humidityArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidityTitle.sizePolicy().hasHeightForWidth())
        self.humidityTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.humidityTitle.setFont(font)
        self.humidityTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.humidityTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.humidityTitle.setObjectName("humidityTitle")
        self.verticalLayout_13.addWidget(self.humidityTitle)
        self.humidity = QtWidgets.QWidget(self.humidityArea)
        self.humidity.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.humidity.setObjectName("humidity")
        self.verticalLayout_13.addWidget(self.humidity)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 5)
        self.verticalLayout_4.addWidget(self.humidityArea)
        self.preasureArea = QtWidgets.QFrame(self.section2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preasureArea.sizePolicy().hasHeightForWidth())
        self.preasureArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.preasureArea.setFont(font)
        self.preasureArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.preasureArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.preasureArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.preasureArea.setObjectName("preasureArea")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.preasureArea)
        self.verticalLayout_14.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.preasureTitle = QtWidgets.QLabel(self.preasureArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preasureTitle.sizePolicy().hasHeightForWidth())
        self.preasureTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.preasureTitle.setFont(font)
        self.preasureTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.preasureTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.preasureTitle.setObjectName("preasureTitle")
        self.verticalLayout_14.addWidget(self.preasureTitle)
        self.preasure = QtWidgets.QWidget(self.preasureArea)
        self.preasure.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.preasure.setObjectName("preasure")
        self.verticalLayout_14.addWidget(self.preasure)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 5)
        self.verticalLayout_4.addWidget(self.preasureArea)
        self.horizontalLayout.addWidget(self.section2)
        self.section3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section3.sizePolicy().hasHeightForWidth())
        self.section3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(10)
        self.section3.setFont(font)
        self.section3.setStyleSheet("")
        self.section3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.section3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.section3.setObjectName("section3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.section3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gpsArea = QtWidgets.QFrame(self.section3)
        self.gpsArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.gpsArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpsArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpsArea.setObjectName("gpsArea")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gpsArea)
        self.verticalLayout_17.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gpsTitle = QtWidgets.QLabel(self.gpsArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpsTitle.sizePolicy().hasHeightForWidth())
        self.gpsTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.gpsTitle.setFont(font)
        self.gpsTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.gpsTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.gpsTitle.setObjectName("gpsTitle")
        self.verticalLayout_17.addWidget(self.gpsTitle)
        self.gps = QtWidgets.QWidget(self.gpsArea)
        self.gps.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.gps.setObjectName("gps")
        self.verticalLayout_17.addWidget(self.gps)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 5)
        self.verticalLayout_11.addWidget(self.gpsArea)
        self.temperatureArea = QtWidgets.QFrame(self.section3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureArea.sizePolicy().hasHeightForWidth())
        self.temperatureArea.setSizePolicy(sizePolicy)
        self.temperatureArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.temperatureArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperatureArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temperatureArea.setObjectName("temperatureArea")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.temperatureArea)
        self.verticalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.temperatureTitle = QtWidgets.QLabel(self.temperatureArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureTitle.sizePolicy().hasHeightForWidth())
        self.temperatureTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.temperatureTitle.setFont(font)
        self.temperatureTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.temperatureTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureTitle.setObjectName("temperatureTitle")
        self.verticalLayout_16.addWidget(self.temperatureTitle)
        self.temperature = QtWidgets.QWidget(self.temperatureArea)
        self.temperature.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.temperature.setObjectName("temperature")
        self.verticalLayout_16.addWidget(self.temperature)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 5)
        self.verticalLayout_11.addWidget(self.temperatureArea)
        self.accelerometerArea = QtWidgets.QFrame(self.section3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerometerArea.sizePolicy().hasHeightForWidth())
        self.accelerometerArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accelerometerArea.setFont(font)
        self.accelerometerArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.accelerometerArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accelerometerArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accelerometerArea.setObjectName("accelerometerArea")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.accelerometerArea)
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.accelerometerTitle = QtWidgets.QLabel(self.accelerometerArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accelerometerTitle.sizePolicy().hasHeightForWidth())
        self.accelerometerTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.accelerometerTitle.setFont(font)
        self.accelerometerTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.accelerometerTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.accelerometerTitle.setObjectName("accelerometerTitle")
        self.verticalLayout_15.addWidget(self.accelerometerTitle)
        self.accelerometer = QtWidgets.QWidget(self.accelerometerArea)
        self.accelerometer.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.accelerometer.setObjectName("accelerometer")
        self.verticalLayout_15.addWidget(self.accelerometer)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 5)
        self.verticalLayout_11.addWidget(self.accelerometerArea)
        self.horizontalLayout.addWidget(self.section3)
        self.section4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section4.sizePolicy().hasHeightForWidth())
        self.section4.setSizePolicy(sizePolicy)
        self.section4.setStyleSheet("")
        self.section4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.section4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.section4.setObjectName("section4")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.section4)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(5)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.errorArea = QtWidgets.QFrame(self.section4)
        self.errorArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.errorArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errorArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.errorArea.setObjectName("errorArea")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.errorArea)
        self.verticalLayout_19.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_19.setSpacing(5)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.errorTitle = QtWidgets.QLabel(self.errorArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorTitle.sizePolicy().hasHeightForWidth())
        self.errorTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.errorTitle.setFont(font)
        self.errorTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.errorTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.errorTitle.setObjectName("errorTitle")
        self.verticalLayout_19.addWidget(self.errorTitle)
        self.errorSet = QtWidgets.QFrame(self.errorArea)
        self.errorSet.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.errorSet.setObjectName("errorSet")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.errorSet)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.error1 = QtWidgets.QLabel(self.errorSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error1.sizePolicy().hasHeightForWidth())
        self.error1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.error1.setFont(font)
        self.error1.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 3px;\n"
"color: rgb(255, 255, 255);")
        self.error1.setAlignment(QtCore.Qt.AlignCenter)
        self.error1.setObjectName("error1")
        self.horizontalLayout_18.addWidget(self.error1)
        self.error2 = QtWidgets.QLabel(self.errorSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error2.sizePolicy().hasHeightForWidth())
        self.error2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.error2.setFont(font)
        self.error2.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 3px;\n"
"color: rgb(255, 255, 255);")
        self.error2.setAlignment(QtCore.Qt.AlignCenter)
        self.error2.setObjectName("error2")
        self.horizontalLayout_18.addWidget(self.error2)
        self.error3 = QtWidgets.QLabel(self.errorSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error3.sizePolicy().hasHeightForWidth())
        self.error3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.error3.setFont(font)
        self.error3.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 3px;\n"
"color: rgb(255, 255, 255);")
        self.error3.setAlignment(QtCore.Qt.AlignCenter)
        self.error3.setObjectName("error3")
        self.horizontalLayout_18.addWidget(self.error3)
        self.error4 = QtWidgets.QLabel(self.errorSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error4.sizePolicy().hasHeightForWidth())
        self.error4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.error4.setFont(font)
        self.error4.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 3px;\n"
"color: rgb(255, 255, 255);")
        self.error4.setAlignment(QtCore.Qt.AlignCenter)
        self.error4.setObjectName("error4")
        self.horizontalLayout_18.addWidget(self.error4)
        self.error5 = QtWidgets.QLabel(self.errorSet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error5.sizePolicy().hasHeightForWidth())
        self.error5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.error5.setFont(font)
        self.error5.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 3px;\n"
"color: rgb(255, 255, 255);")
        self.error5.setAlignment(QtCore.Qt.AlignCenter)
        self.error5.setObjectName("error5")
        self.horizontalLayout_18.addWidget(self.error5)
        self.verticalLayout_19.addWidget(self.errorSet)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 5)
        self.verticalLayout_24.addWidget(self.errorArea)
        self.gyroArea = QtWidgets.QFrame(self.section4)
        self.gyroArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.gyroArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gyroArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gyroArea.setObjectName("gyroArea")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.gyroArea)
        self.verticalLayout_20.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gyroTitle = QtWidgets.QLabel(self.gyroArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gyroTitle.sizePolicy().hasHeightForWidth())
        self.gyroTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.gyroTitle.setFont(font)
        self.gyroTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.gyroTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.gyroTitle.setObjectName("gyroTitle")
        self.verticalLayout_20.addWidget(self.gyroTitle)
        self.gyro = QtWidgets.QOpenGLWidget(self.gyroArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gyro.sizePolicy().hasHeightForWidth())
        self.gyro.setSizePolicy(sizePolicy)
        self.gyro.setObjectName("gyro")
        self.verticalLayout_20.addWidget(self.gyro)
        self.xArea = QtWidgets.QHBoxLayout()
        self.xArea.setContentsMargins(10, -1, 10, -1)
        self.xArea.setObjectName("xArea")
        self.xTitle = QtWidgets.QLabel(self.gyroArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xTitle.sizePolicy().hasHeightForWidth())
        self.xTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.xTitle.setFont(font)
        self.xTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.xTitle.setObjectName("xTitle")
        self.xArea.addWidget(self.xTitle)
        self.xValue = QtWidgets.QLabel(self.gyroArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.xValue.setFont(font)
        self.xValue.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.xValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xValue.setObjectName("xValue")
        self.xArea.addWidget(self.xValue)
        self.verticalLayout_20.addLayout(self.xArea)
        self.yArea = QtWidgets.QHBoxLayout()
        self.yArea.setContentsMargins(10, -1, 10, -1)
        self.yArea.setObjectName("yArea")
        self.yTitle = QtWidgets.QLabel(self.gyroArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yTitle.sizePolicy().hasHeightForWidth())
        self.yTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(14)
        self.yTitle.setFont(font)
        self.yTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.yTitle.setObjectName("yTitle")
        self.yArea.addWidget(self.yTitle)
        self.yValue = QtWidgets.QLabel(self.gyroArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.yValue.setFont(font)
        self.yValue.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.yValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yValue.setObjectName("yValue")
        self.yArea.addWidget(self.yValue)
        self.verticalLayout_20.addLayout(self.yArea)
        self.zArea = QtWidgets.QHBoxLayout()
        self.zArea.setContentsMargins(10, -1, 10, -1)
        self.zArea.setObjectName("zArea")
        self.zTitle = QtWidgets.QLabel(self.gyroArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zTitle.sizePolicy().hasHeightForWidth())
        self.zTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.zTitle.setFont(font)
        self.zTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.zTitle.setObjectName("zTitle")
        self.zArea.addWidget(self.zTitle)
        self.zValue = QtWidgets.QLabel(self.gyroArea)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.zValue.setFont(font)
        self.zValue.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.zValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zValue.setObjectName("zValue")
        self.zArea.addWidget(self.zValue)
        self.verticalLayout_20.addLayout(self.zArea)
        self.verticalLayout_20.setStretch(0, 1)
        self.verticalLayout_20.setStretch(1, 7)
        self.verticalLayout_20.setStretch(2, 1)
        self.verticalLayout_20.setStretch(3, 1)
        self.verticalLayout_20.setStretch(4, 1)
        self.verticalLayout_24.addWidget(self.gyroArea)
        self.speedArea = QtWidgets.QFrame(self.section4)
        self.speedArea.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 1px solid #fff;\n"
"border-radius: 7px;")
        self.speedArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speedArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speedArea.setObjectName("speedArea")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.speedArea)
        self.verticalLayout_23.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_23.setSpacing(5)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.speedTitle = QtWidgets.QLabel(self.speedArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedTitle.sizePolicy().hasHeightForWidth())
        self.speedTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(16)
        self.speedTitle.setFont(font)
        self.speedTitle.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;\n"
"color: rgb(255, 255, 255);")
        self.speedTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.speedTitle.setObjectName("speedTitle")
        self.verticalLayout_23.addWidget(self.speedTitle)
        self.speed = QtWidgets.QWidget(self.speedArea)
        self.speed.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"border: 0px solid #fff;\n"
"border-radius: 7px;")
        self.speed.setObjectName("speed")
        self.verticalLayout_23.addWidget(self.speed)
        self.verticalLayout_23.setStretch(0, 1)
        self.verticalLayout_23.setStretch(1, 5)
        self.verticalLayout_24.addWidget(self.speedArea)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.setStretch(1, 5)
        self.verticalLayout_24.setStretch(2, 3)
        self.horizontalLayout.addWidget(self.section4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        theVoid.setCentralWidget(self.centralwidget)

        self.retranslateUi(theVoid)
        QtCore.QMetaObject.connectSlotsByName(theVoid)

    def retranslateUi(self, theVoid):
        _translate = QtCore.QCoreApplication.translate
        theVoid.setWindowTitle(_translate("theVoid", "the.void"))
        self.teamNo.setText(_translate("theVoid", "TEAM NO"))
        self.infoTitle.setText(_translate("theVoid", "INFO"))
        self.connectButton.setText(_translate("theVoid", "CONNECT"))
        self.ipTitle.setText(_translate("theVoid", "IP:"))
        self.portTitle.setText(_translate("theVoid", "PORT:"))
        self.portDataList.setItemText(0, _translate("theVoid", "123"))
        self.portDataList.setItemText(1, _translate("theVoid", "456"))
        self.portDataList.setItemText(2, _translate("theVoid", "789"))
        self.baudrateTitle.setText(_translate("theVoid", "BAUDRATE:"))
        self.liveTimeName.setText(_translate("theVoid", "TIME"))
        self.liveTimeValue.setText(_translate("theVoid", "12:00"))
        self.startTimeName.setText(_translate("theVoid", "START"))
        self.startTimeValue.setText(_translate("theVoid", "12:00"))
        self.disconnectTime.setText(_translate("theVoid", "DISCONNECT"))
        self.disconnectTimeValue.setText(_translate("theVoid", "12:00"))
        self.downTimeName.setText(_translate("theVoid", "DOWN"))
        self.downTimeValue.setToolTip(_translate("theVoid", "<html><head/><body><p>12:00</p></body></html>"))
        self.downTimeValue.setText(_translate("theVoid", "12:00"))
        self.totalTimeName.setText(_translate("theVoid", "TOTAL"))
        self.totalTimeValue.setText(_translate("theVoid", "12:00"))
        self.fileInput.setText(_translate("theVoid", "name.mp4"))
        self.chooseButton.setText(_translate("theVoid", "CHOOSE"))
        self.sendButton.setText(_translate("theVoid", "SEND"))
        self.startButton.setText(_translate("theVoid", "START"))
        self.buzzerButton.setText(_translate("theVoid", "BUZZER"))
        self.gpsButton.setText(_translate("theVoid", "GPS"))
        self.cameraButton.setText(_translate("theVoid", "CAMERA"))
        self.gyroButton.setText(_translate("theVoid", "GYRO"))
        self.disconnectButton.setText(_translate("theVoid", "DISCONNECT"))
        self.preasureButton.setText(_translate("theVoid", "PREASURE"))
        self.terminalTitle.setText(_translate("theVoid", "TERMINAL"))
        self.terminalScreen.setHtml(_translate("theVoid", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Terminal\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#f3ff00;\">connecting...</span></p></body></html>"))
        self.cameraTitle.setText(_translate("theVoid", "CAMERA"))
        self.humidityTitle.setText(_translate("theVoid", "HUMIDITY"))
        self.preasureTitle.setText(_translate("theVoid", "PREASURE"))
        self.gpsTitle.setText(_translate("theVoid", "GPS"))
        self.temperatureTitle.setText(_translate("theVoid", "TEMPERATURE"))
        self.accelerometerTitle.setText(_translate("theVoid", "ACCELEROMETER"))
        self.errorTitle.setText(_translate("theVoid", "ERROR"))
        self.error1.setText(_translate("theVoid", "1"))
        self.error2.setText(_translate("theVoid", "2"))
        self.error3.setText(_translate("theVoid", "3"))
        self.error4.setText(_translate("theVoid", "4"))
        self.error5.setText(_translate("theVoid", "5"))
        self.gyroTitle.setText(_translate("theVoid", "GYRO"))
        self.xTitle.setText(_translate("theVoid", "X:"))
        self.xValue.setText(_translate("theVoid", "123"))
        self.yTitle.setText(_translate("theVoid", "Y:"))
        self.yValue.setText(_translate("theVoid", "456"))
        self.zTitle.setText(_translate("theVoid", "Z:"))
        self.zValue.setText(_translate("theVoid", "789"))
        self.speedTitle.setText(_translate("theVoid", "SPEED"))
# import assets_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    theVoid = QtWidgets.QMainWindow()
    ui = Ui_theVoid()
    ui.setupUi(theVoid)
    theVoid.show()
    sys.exit(app.exec_())
